apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-console-deployment
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-console
  template:
    metadata:
      labels:
        app: kafka-console
    spec:
      containers:
        - name: kafka-console
          image: docker.redpanda.com/redpandadata/console:v2.7.2
          ports:
            - containerPort: 8080
          env:
            - name: CONFIG_FILEPATH
              value: /tmp/config.yml
            - name: CONSOLE_CONFIG_FILE
              value: |
                kafka:
                  brokers: ["kafka-service:9092"]
          volumeMounts:
            - mountPath: /tmp
              name: config-volume
      volumes:
        - name: config-volume
          emptyDir: {}

