apiVersion: apps/v1
kind: Deployment
metadata:
  name: console
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: console
  template:
    metadata:
      labels:
        app: console
    spec:
      containers:
        - name: console
          image: docker.redpanda.com/redpandadata/console:v2.7.2
          command: ["/bin/sh", "-c", "echo \"$$CONSOLE_CONFIG_FILE\" > /tmp/config.yml; /app/console"]
          env:
            - name: CONFIG_FILEPATH
              value: "/tmp/config.yml"
            - name: CONSOLE_CONFIG_FILE
              value: |
                kafka:
                  brokers: ["kafka1:19092"]
          ports:
            - containerPort: 8080