apiVersion: v1
kind: Service
metadata:
  name: kafka1
  namespace: development
spec:
  selector:
    app: kafka
  ports:
    - name: internal
      port: 9093
      targetPort: 9093
    - name: external
      port: 29092
      targetPort: 29092
    - name: jmx
      port: 9999
      targetPort: 9999
