apiVersion: v1
kind: Service
metadata:
  name: kafka1
spec:
  ports:
    - port: 9093
      targetPort: 9093
    - port: 29092
      targetPort: 29092
    - port: 9999
      targetPort: 9999
  selector:
    app: kafka
