apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-deployment
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: confluentinc/cp-zookeeper:7.3.2
          ports:
            - containerPort: 2181
          volumeMounts:
            - mountPath: /var/lib/zookeeper/data
              name: zookeeper-data
      volumes:
        - name: zookeeper-data
          persistentVolumeClaim:
            claimName: zookeeper-data-pvc

