apiVersion: apps/v1
kind: Deployment
metadata:
  name: zoo1
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: confluentinc/cp-zookeeper:7.3.2
          ports:
            - containerPort: 2181
          environment:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_SERVER_ID
              value: "1"
            - name: ZOOKEEPER_SERVERS
              value: "zoo1:2888:3888"
          volumes:
            - name: zookeeper_data
              persistentVolumeClaim:
                claimName: zookeeper-pvc
            - name: zookeeper_log
              persistentVolumeClaim:
                claimName: zookeeper-log-pvc
